FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    postgresql-client \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p static

EXPOSE 8000

# Увеличиваем время ожидания до 20 секунд
CMD sh -c "sleep 20 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"