services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: athletelink_backend
    command: >
      sh -c "sleep 10 &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: athletelink_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:8000
      - PING_MESSAGE="ping pong"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: athletelink_postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
      # - POSTGRES_HOST_AUTH_METHOD=trust <----- ЭТО ВЗЛОМАЕТ НАМ ЖОПУ НЕ ОТКОММЕНЧИВАТЬ
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
