# Generated by Django 5.2.6 on 2025-11-30 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Название события')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('sport', models.CharField(max_length=100, verbose_name='Вид спорта')),
                ('status', models.CharField(choices=[('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('completed', 'Завершена'), ('pending', 'На рассмотрении')], default='pending', max_length=20, verbose_name='Статус')),
                ('game_result', models.CharField(choices=[('na', 'Н/Д'), ('cancelled', 'Отменена'), ('victory', 'Победа'), ('defeat', 'Поражение')], default='na', max_length=20, verbose_name='Результат игры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-date'],
            },
        ),
    ]
