# Generated by Django 5.2.6 on 2025-12-01 21:40

import app.requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название события')),
                ('players_count', models.PositiveIntegerField(verbose_name='Количество игроков')),
                ('event_date', models.DateTimeField(default=app.requests.models.get_default_event_date, verbose_name='Дата и время события')),
                ('location', models.CharField(default='Москва', max_length=255, verbose_name='Место проведения')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('game_result_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Результат (текст)')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'requests',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название спорта')),
                ('min_required_players', models.PositiveIntegerField(default=2, verbose_name='Минимальное кол-во игроков')),
                ('max_required_players', models.PositiveIntegerField(default=20, verbose_name='Максимальное кол-во игроков')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
                'db_table': 'sports',
            },
        ),
    ]
