# Generated by Django 5.2.6 on 2025-11-30 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrequest',
            name='request_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создать заявки'),
        ),
        migrations.AddField(
            model_name='activityrequest',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.sport', verbose_name='Вид спорта'),
        ),
    ]
