# Generated by Django 5.2.6 on 2025-12-01 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrequest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_requests', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='activityrequest',
            name='request_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создать заявки'),
        ),
        migrations.AddField(
            model_name='activityrequest',
            name='winner',
            field=models.ManyToManyField(blank=True, related_name='won_requests', to=settings.AUTH_USER_MODEL, verbose_name='Победители'),
        ),
        migrations.AddField(
            model_name='activityrequest',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.sport', verbose_name='Вид спорта'),
        ),
    ]
