# Generated by Django 5.2.6 on 2025-12-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_activityrequest_latitude_activityrequest_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='activityrequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Долгота'),
        ),
    ]
