# Generated by Django 5.2.6 on 2025-12-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_alter_activityrequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Полный URL или относительный путь к SVG/PNG иконке спорта.', null=True),
        ),
    ]
