# Generated by Django 5.2.6 on 2025-12-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_sport_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrequest',
            name='status',
            field=models.CharField(choices=[('planned', 'Игра запланирована'), ('active', 'Игра активна'), ('completed', 'Игра завершена'), ('cancelled', 'Игра отменена')], default='planned', max_length=20, verbose_name='Статус'),
        ),
    ]
