# Generated by Django 5.2.6 on 2025-12-02 22:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Никнейм')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('total_wins', models.PositiveIntegerField(default=0, verbose_name='Всего побед')),
                ('total_losses', models.PositiveIntegerField(default=0, verbose_name='Всего поражений')),
                ('global_rating', models.IntegerField(default=500, verbose_name='Общий рейтинг')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменил'), ('attended', 'Присутствовал')], default='registered', max_length=20, verbose_name='Статус')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.activityrequest', verbose_name='Событие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник события',
                'verbose_name_plural': 'Участники событий',
                'db_table': 'event_participants',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserSportStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='Побед')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='Поражений')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг в спорте')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='requests.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика по спорту',
                'verbose_name_plural': 'Статистика по спорту',
                'unique_together': {('user', 'sport')},
            },
        ),
    ]
