# Generated by Django 5.2.6 on 2025-12-02 20:37

from django.db import migrations
from datetime import date

def create_initial_users(apps, schema_editor):
    # 'user' - это имя приложения, где определена модель User
    User = apps.get_model('user', 'User')

    # Создаем первого пользователя
    if not User.objects.filter(email='testuser1@example.com').exists():
        User.objects.create_user(
            email='testuser1@example.com',
            password='strongpassword123',
            username='userone',
            full_name='Иван Петров',
            telegram='@ivan_petrov_tg',
            birth_date=date(1990, 1, 15),
            city='Москва',
            gender='male',
            bio='Люблю футбол и баскетбол.'
        )

    # Создаем второго пользователя
    if not User.objects.filter(email='testuser2@example.com').exists():
        User.objects.create_user(
            email='testuser2@example.com',
            password='anothersecurepass',
            username='usertwo',
            full_name='Анна Сидорова',
            telegram='@anna_sidorova_tg',
            birth_date=date(1995, 5, 20),
            city='Санкт-Петербург',
            gender='female',
            bio='Активный игрок в теннис и волейбол.'
        )

class Migration(migrations.Migration):

    dependencies = [
        # Зависимость от миграции, которая создает модель User
        ('user', '0001_initial'), 
        # Зависимость от последней миграции в приложении requests
        ('requests', '0004_remove_activityrequest_game_result_text_and_more'), 
    ]

    operations = [
        migrations.RunPython(create_initial_users, migrations.RunPython.noop),
    ]