# Generated by Django 5.2.6 on 2025-12-02 20:37

from django.db import migrations
from datetime import date

def create_initial_users(apps, schema_editor):
    # 'user' - это имя приложения, где определена модель User
    User = apps.get_model('user', 'User')

    from django.contrib.auth.hashers import make_password

    # Создаем первого пользователя - ВРУЧНУЮ, без create_user()
    if not User.objects.filter(email='test1@example.com').exists():
        user1 = User(
            email='test1@example.com',
            username='user1',
            full_name='Иван Петров',
            telegram='@ivan_petrov_tg',
            birth_date=date(1990, 1, 15),
            city='Москва',
            gender='male',
            bio='Люблю футбол и баскетбол.',
            is_active=True,
            is_staff=False,
            is_superuser=False
        )
        user1.password = make_password('sigma2007')  # Хэшируем пароль вручную
        user1.save()

    # Создаем второго пользователя
    if not User.objects.filter(email='test2@example.com').exists():
        user2 = User(
            email='test2@example.com',
            username='user2',
            full_name='Анна Сидорова',
            telegram='@anna_sidorova_tg',
            birth_date=date(1995, 5, 20),
            city='Санкт-Петербург',
            gender='female',
            bio='Активный игрок в теннис и волейбол.',
            is_active=True,
            is_staff=False,
            is_superuser=False
        )
        user2.password = make_password('sigma2007')
        user2.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_initial_users, migrations.RunPython.noop),
        
    ]
