# Generated by Django 5.2.6 on 2025-11-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_event_organizer_alter_eventparticipant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
