# Generated by Django 5.2.6 on 2025-12-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='global_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prestige_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersportstats',
            name='sport_rank_name',
            field=models.CharField(default='Искра I', max_length=50),
        ),
        migrations.AddField(
            model_name='usersportstats',
            name='win_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='global_rating',
            field=models.IntegerField(default=0, verbose_name='Общий рейтинг'),
        ),
    ]
