# Generated by Django 5.2.6 on 2025-12-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_global_rank_user_prestige_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_tier', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Ранг',
                'verbose_name_plural': 'Ранги',
            },
        ),
    ]
