# Generated by Django 5.2.6 on 2025-12-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_ranktier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RankTier',
        ),
    ]
