# Generated by Django 5.2.6 on 2025-12-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_ranktier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_answer_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэш ответа на секретный вопрос'),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_question',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Секретный вопрос'),
        ),
    ]
