# Generated by Django 5.2.6 on 2025-12-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_ranktier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], default='Не указан', max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
