# Generated by Django 5.2.6 on 2025-12-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_gender'),
        ('user', '0006_user_secret_answer_hash_user_secret_question'),
    ]

    operations = [
    ]
